language: node_js
node_js:
  - "8.5"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - node index.js download
  - node index.js generate-json
  - yarn test
after_success:
  - .travis/push.sh
